In [1]:
import numpy as np
x= np.array([[1,2,3],[4,5,6]])
print ("x:\n{}".format(x))

x:
[[1 2 3]
 [4 5 6]]


In [2]:
from scipy import sparse 
eye = np.eye(4)
print("Numpy array:\n{}".format(eye))

Numpy array:
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [3]:
from sklearn.datasets import load_iris
iris_dataset= load_iris()

In [4]:
print(format(iris_dataset.keys()))

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])


In [37]:
[print(iris_dataset['DESCR'][0: 200]+ "\n...")]

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes
...


[None]

In [6]:

print(format(iris_dataset['target_names']))

['setosa' 'versicolor' 'virginica']


In [7]:
print(type(iris_dataset['data']))

<class 'numpy.ndarray'>


In [8]:
print(iris_dataset['data'].shape)

(150, 4)


In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(
    iris_dataset['data'], iris_dataset['target'], random_state=0)

In [17]:
import sys
import pandas as pd
import matplotlib
import numpy as np
import scipy as sp 
import IPython
import sklearn
import mglearn
from IPython.display import display
import matplotlib.pyplot as plt

In [11]:
print(X_train)

[[ 5.9  3.   4.2  1.5]
 [ 5.8  2.6  4.   1.2]
 [ 6.8  3.   5.5  2.1]
 [ 4.7  3.2  1.3  0.2]
 [ 6.9  3.1  5.1  2.3]
 [ 5.   3.5  1.6  0.6]
 [ 5.4  3.7  1.5  0.2]
 [ 5.   2.   3.5  1. ]
 [ 6.5  3.   5.5  1.8]
 [ 6.7  3.3  5.7  2.5]
 [ 6.   2.2  5.   1.5]
 [ 6.7  2.5  5.8  1.8]
 [ 5.6  2.5  3.9  1.1]
 [ 7.7  3.   6.1  2.3]
 [ 6.3  3.3  4.7  1.6]
 [ 5.5  2.4  3.8  1.1]
 [ 6.3  2.7  4.9  1.8]
 [ 6.3  2.8  5.1  1.5]
 [ 4.9  2.5  4.5  1.7]
 [ 6.3  2.5  5.   1.9]
 [ 7.   3.2  4.7  1.4]
 [ 6.5  3.   5.2  2. ]
 [ 6.   3.4  4.5  1.6]
 [ 4.8  3.1  1.6  0.2]
 [ 5.8  2.7  5.1  1.9]
 [ 5.6  2.7  4.2  1.3]
 [ 5.6  2.9  3.6  1.3]
 [ 5.5  2.5  4.   1.3]
 [ 6.1  3.   4.6  1.4]
 [ 7.2  3.2  6.   1.8]
 [ 5.3  3.7  1.5  0.2]
 [ 4.3  3.   1.1  0.1]
 [ 6.4  2.7  5.3  1.9]
 [ 5.7  3.   4.2  1.2]
 [ 5.4  3.4  1.7  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 6.9  3.1  4.9  1.5]
 [ 4.6  3.1  1.5  0.2]
 [ 5.9  3.   5.1  1.8]
 [ 5.1  2.5  3.   1.1]
 [ 4.6  3.4  1.4  0.3]
 [ 6.2  2.2  4.5  1.5]
 [ 7.2  3.6  6.1  2.5]
 [ 5.7  2.9

In [23]:
print(X_train.shape)

(112, 4)


In [13]:
print(.75* 150)

112.5


In [18]:
iris_dataframe= pd.DataFrame(X_train,columns=iris_dataset.feature_names)
grr=pd.plotting.scatter_matrix(iris_dataframe,c=Y_train, figsize=(15,15),marker='o',
                     hist_kwds={'bins':20},s=60, alpha=.8, cmap=mglearn.cm3)


AttributeError: 'numpy.ndarray' object has no attribute 'plot'

In [20]:
plt.show()

In [25]:
from sklearn.neighbors import KNeighborsClassifier
knn= KNeighborsClassifier(n_neighbors=1)

In [27]:
knn.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [30]:
X_new=np.array([[5,2.9,1,0.2]])
print(X_new.shape)

(1, 4)


In [32]:
prediction= knn.predict(X_new)
print(prediction)
print(format(iris_dataset['target_names'][prediction]))

[0]
['setosa']


In [33]:
y_pred= knn.predict(X_test)
print(y_pred)

[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [35]:
print(np.mean(y_pred==Y_test))

0.973684210526
